title       = "bc"
baseURL     = "https://barchart-cli.tamnd.com/"
description = "Browse Barchart stock market data"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/barchart-cli"
